import { Raleway } from 'next/font/google';
import './globals.css';
import Navigation from './components/navigation/navigation';
import Link from 'next/link';
import Footer from './components/footer/footer';

const raleway = Raleway({ subsets: ['latin'] });

export const metadata = {
	title: 'Portfolio - Tiia Pitkänen',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={raleway.className}>
				<Navigation />
				{children}
				<Footer />
			</body>
		</html>
	);
}
