import { Raleway } from 'next/font/google';
import './globals.css';
import Navigation from './components/navigation/navigation';
import Link from 'next/link';

const raleway = Raleway({ subsets: ['latin'] });

export const metadata = {
	title: 'Portfolio - Tiia Pitkänen',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<Navigation />
			<body className={raleway.className}>{children}</body>
		</html>
	);
}
